/**
 * Checkout Advice System - Gummi Lilli
 * Professional dart checkout recommendations with alternatives
 * 
 * Format:
 * S = Single (einfaldur)
 * D = Double (tvöfaldur)
 * T = Triple (þrefaldur)
 * SB = Single Bull (25 stig)
 * DB = Double Bull (50 stig - bull's eye)
 */

const checkoutAdvice = {
    2: { tegund: "Útgangur", maelt_med: "D1", varaleid: null, athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    3: { tegund: "Útgangur", maelt_med: "S1, D1", varaleid: null, athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    4: { tegund: "Útgangur", maelt_med: "D2", varaleid: "S2, D1", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    5: { tegund: "Útgangur", maelt_med: "S1, D2", varaleid: "T1, D1", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    6: { tegund: "Útgangur", maelt_med: "D3", varaleid: "D1, D2", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    7: { tegund: "Útgangur", maelt_med: "S3, D2", varaleid: "S3, D2", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    8: { tegund: "Útgangur", maelt_med: "D4", varaleid: "S4, D2", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    9: { tegund: "Útgangur", maelt_med: "S1, D4", varaleid: "S5, D2", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    10: { tegund: "Útgangur", maelt_med: "D5", varaleid: "D1, D4", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    11: { tegund: "Útgangur", maelt_med: "S7, D2", varaleid: "S3, D4", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    12: { tegund: "Útgangur", maelt_med: "D6", varaleid: "S4, D4", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    13: { tegund: "Útgangur", maelt_med: "S9, D2", varaleid: "S5, D4", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    14: { tegund: "Útgangur", maelt_med: "D7", varaleid: "D1, D6", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    15: { tegund: "Útgangur", maelt_med: "S7, D4", varaleid: "S3, D6", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    16: { tegund: "Útgangur", maelt_med: "D8", varaleid: "S4, D6", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    17: { tegund: "Útgangur", maelt_med: "S1, D8", varaleid: "S5, D6", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    18: { tegund: "Útgangur", maelt_med: "D9", varaleid: "D1, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    19: { tegund: "Útgangur", maelt_med: "S3, D8", varaleid: "S3, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    20: { tegund: "Útgangur", maelt_med: "D10", varaleid: "D2, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    21: { tegund: "Útgangur", maelt_med: "S5, D8", varaleid: "T1, S2, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    22: { tegund: "Útgangur", maelt_med: "D11", varaleid: "S6, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    23: { tegund: "Útgangur", maelt_med: "S7, D8", varaleid: "T2, S1, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    24: { tegund: "Útgangur", maelt_med: "D12", varaleid: "D4, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    25: { tegund: "Útgangur", maelt_med: "S9, D8", varaleid: "T3, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    26: { tegund: "Útgangur", maelt_med: "D13", varaleid: "D5, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    27: { tegund: "Útgangur", maelt_med: "S11, D8", varaleid: "S8, T1, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    28: { tegund: "Útgangur", maelt_med: "D14", varaleid: "T4, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    29: { tegund: "Útgangur", maelt_med: "S13, D8", varaleid: "S12, S1, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    30: { tegund: "Útgangur", maelt_med: "D15", varaleid: "D7, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    31: { tegund: "Útgangur", maelt_med: "S15, D8", varaleid: "T5, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    32: { tegund: "Útgangur", maelt_med: "D16", varaleid: "S16, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    33: { tegund: "Útgangur", maelt_med: "S17, D8", varaleid: "S17, D8", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    34: { tegund: "Útgangur", maelt_med: "D17", varaleid: "D1, D16", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    35: { tegund: "Útgangur", maelt_med: "S19, D8", varaleid: "S3, D16", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    36: { tegund: "Útgangur", maelt_med: "D18", varaleid: "D2, D16", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    37: { tegund: "Útgangur", maelt_med: "S17, D10", varaleid: "T1, S2, D16", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    38: { tegund: "Útgangur", maelt_med: "D19", varaleid: "S6, D16", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    39: { tegund: "Útgangur", maelt_med: "S19, D10", varaleid: "T2, S1, D16", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    40: { tegund: "Útgangur", maelt_med: "D20", varaleid: "S8, D16", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    41: { tegund: "Útgangur", maelt_med: "S9, D16", varaleid: "S9, D16", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    42: { tegund: "Útgangur", maelt_med: "S10, D16", varaleid: "D1, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    43: { tegund: "Útgangur", maelt_med: "S11, D16", varaleid: "S3, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    44: { tegund: "Útgangur", maelt_med: "S12, D16", varaleid: "D2, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    45: { tegund: "Útgangur", maelt_med: "S13, D16", varaleid: "T1, S2, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    46: { tegund: "Útgangur", maelt_med: "S14, D16", varaleid: "S6, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    47: { tegund: "Útgangur", maelt_med: "S15, D16", varaleid: "T2, S1, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    48: { tegund: "Útgangur", maelt_med: "S16, D16", varaleid: "D4, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    49: { tegund: "Útgangur", maelt_med: "S17, D16", varaleid: "T3, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    50: { tegund: "Útgangur", maelt_med: "S10, D20", varaleid: "DB", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    51: { tegund: "Útgangur", maelt_med: "S19, D16", varaleid: "S8, T1, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    52: { tegund: "Útgangur", maelt_med: "S20, D16", varaleid: "T4, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    53: { tegund: "Útgangur", maelt_med: "S13, D20", varaleid: "S12, S1, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    54: { tegund: "Útgangur", maelt_med: "S14, D20", varaleid: "D7, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    55: { tegund: "Útgangur", maelt_med: "S15, D20", varaleid: "T5, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    56: { tegund: "Útgangur", maelt_med: "S16, D20", varaleid: "D8, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    57: { tegund: "Útgangur", maelt_med: "S17, D20", varaleid: "S16, S1, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    58: { tegund: "Útgangur", maelt_med: "S18, D20", varaleid: "T6, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    59: { tegund: "Útgangur", maelt_med: "S19, D20", varaleid: "S18, S1, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    60: { tegund: "Útgangur", maelt_med: "S20, D20", varaleid: "D10, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    61: { tegund: "Útgangur", maelt_med: "T7, D20", varaleid: "S20, S1, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    62: { tegund: "Útgangur", maelt_med: "D11, D20", varaleid: "S20, S2, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    63: { tegund: "Útgangur", maelt_med: "S20, T1, D20", varaleid: "S20, S3, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    64: { tegund: "Útgangur", maelt_med: "T8, D20", varaleid: "D12, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    65: { tegund: "Útgangur", maelt_med: "SB, D20", varaleid: "S20, S5, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    66: { tegund: "Útgangur", maelt_med: "D13, D20", varaleid: "S20, T2, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    67: { tegund: "Útgangur", maelt_med: "T9, D20", varaleid: "S20, S7, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    68: { tegund: "Útgangur", maelt_med: "D14, D20", varaleid: "S20, S8, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    69: { tegund: "Útgangur", maelt_med: "S20, S9, D20", varaleid: "S20, T3, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    70: { tegund: "Útgangur", maelt_med: "T10, D20", varaleid: "D15, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    71: { tegund: "Útgangur", maelt_med: "S20, S11, D20", varaleid: "S19, S12, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    72: { tegund: "Útgangur", maelt_med: "D16, D20", varaleid: "S20, S12, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    73: { tegund: "Útgangur", maelt_med: "T11, D20", varaleid: "S20, S13, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    74: { tegund: "Útgangur", maelt_med: "D17, D20", varaleid: "S20, S14, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    75: { tegund: "Útgangur", maelt_med: "S20, S15, D20", varaleid: "S19, S16, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    76: { tegund: "Útgangur", maelt_med: "T12, D20", varaleid: "D18, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    77: { tegund: "Útgangur", maelt_med: "S20, S17, D20", varaleid: "S19, S18, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    78: { tegund: "Útgangur", maelt_med: "D19, D20", varaleid: "S20, S18, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    79: { tegund: "Útgangur", maelt_med: "T13, D20", varaleid: "S20, S19, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    80: { tegund: "Útgangur", maelt_med: "D20, D20", varaleid: "S20, S20, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    81: { tegund: "Útgangur", maelt_med: "S20, T7, D20", varaleid: "S17, T8, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    82: { tegund: "Útgangur", maelt_med: "T14, D20", varaleid: "S18, T8, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    83: { tegund: "Útgangur", maelt_med: "S19, T8, D20", varaleid: "S18, SB, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    84: { tegund: "Útgangur", maelt_med: "S20, T8, D20", varaleid: "S19, SB, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    85: { tegund: "Útgangur", maelt_med: "T15, D20", varaleid: "S20, SB, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    86: { tegund: "Útgangur", maelt_med: "S19, T9, D20", varaleid: "T15, S1, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    87: { tegund: "Útgangur", maelt_med: "S20, T9, D20", varaleid: "T15, S2, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    88: { tegund: "Útgangur", maelt_med: "T16, D20", varaleid: "S18, T10, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    89: { tegund: "Útgangur", maelt_med: "T16, S1, D20", varaleid: "S19, T10, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    90: { tegund: "Útgangur", maelt_med: "DB, D20", varaleid: "S20, T10, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    91: { tegund: "Útgangur", maelt_med: "T17, D20", varaleid: "T16, T1, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    92: { tegund: "Útgangur", maelt_med: "T17, S1, D20", varaleid: "T16, S4, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    93: { tegund: "Útgangur", maelt_med: "T17, S2, D20", varaleid: "S20, T11, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    94: { tegund: "Útgangur", maelt_med: "T18, D20", varaleid: "T17, T1, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    95: { tegund: "Útgangur", maelt_med: "T18, S1, D20", varaleid: "T17, S4, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    96: { tegund: "Útgangur", maelt_med: "T18, S2, D20", varaleid: "T17, S5, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    97: { tegund: "Útgangur", maelt_med: "T19, D20", varaleid: "T18, T1, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    98: { tegund: "Útgangur", maelt_med: "T19, S1, D20", varaleid: "T18, S4, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    99: { tegund: "Útgangur", maelt_med: "T19, S2, D20", varaleid: "T18, S5, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    100: { tegund: "Útgangur", maelt_med: "T20, D20", varaleid: "T19, T1, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    101: { tegund: "Útgangur", maelt_med: "T20, S1, D20", varaleid: "T19, S4, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    102: { tegund: "Útgangur", maelt_med: "T20, S2, D20", varaleid: "T19, S5, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    103: { tegund: "Útgangur", maelt_med: "T20, T1, D20", varaleid: "T20, S3, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    104: { tegund: "Útgangur", maelt_med: "T20, S4, D20", varaleid: "T19, S7, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    105: { tegund: "Útgangur", maelt_med: "T20, S5, D20", varaleid: "T19, S8, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    106: { tegund: "Útgangur", maelt_med: "T20, T2, D20", varaleid: "T20, S6, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    107: { tegund: "Útgangur", maelt_med: "T20, S7, D20", varaleid: "T18, S13, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    108: { tegund: "Útgangur", maelt_med: "T20, S8, D20", varaleid: "T19, S11, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    109: { tegund: "Útgangur", maelt_med: "T20, S9, D20", varaleid: "T20, T3, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    110: { tegund: "Útgangur", maelt_med: "T19, S13, D20", varaleid: "T20, S10, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    111: { tegund: "Útgangur", maelt_med: "T20, S11, D20", varaleid: "T19, S14, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    112: { tegund: "Útgangur", maelt_med: "T20, S12, D20", varaleid: "T19, S15, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    113: { tegund: "Útgangur", maelt_med: "T20, S13, D20", varaleid: "T19, S16, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    114: { tegund: "Útgangur", maelt_med: "T20, S14, D20", varaleid: "T19, S17, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    115: { tegund: "Útgangur", maelt_med: "T20, S15, D20", varaleid: "T19, S18, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    116: { tegund: "Útgangur", maelt_med: "T20, S16, D20", varaleid: "T19, S19, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    117: { tegund: "Útgangur", maelt_med: "T20, S17, D20", varaleid: "T19, S20, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    118: { tegund: "Útgangur", maelt_med: "T20, S18, D20", varaleid: "T20, T6, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    119: { tegund: "Útgangur", maelt_med: "T20, S19, D20", varaleid: "S19, T20, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    120: { tegund: "Útgangur", maelt_med: "T20, S20, D20", varaleid: "S20, T20, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    121: { tegund: "Útgangur", maelt_med: "T20, T7, D20", varaleid: "T19, T8, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    122: { tegund: "Útgangur", maelt_med: "T19, SB, D20", varaleid: "T20, D11, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    123: { tegund: "Útgangur", maelt_med: "T19, D13, D20", varaleid: "T17, D16, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    124: { tegund: "Útgangur", maelt_med: "T20, T8, D20", varaleid: "T19, T9, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    125: { tegund: "Útgangur", maelt_med: "T20, SB, D20", varaleid: "T19, D14, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    126: { tegund: "Útgangur", maelt_med: "T20, D13, D20", varaleid: "T18, D16, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    127: { tegund: "Útgangur", maelt_med: "T20, T9, D20", varaleid: "T19, T10, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    128: { tegund: "Útgangur", maelt_med: "T20, D14, D20", varaleid: "T18, D17, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    129: { tegund: "Útgangur", maelt_med: "T19, D16, D20", varaleid: "T17, D19, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    130: { tegund: "Útgangur", maelt_med: "T20, T10, D20", varaleid: "T18, T12, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    131: { tegund: "Útgangur", maelt_med: "T19, D17, D20", varaleid: "T17, D20, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    132: { tegund: "Útgangur", maelt_med: "T20, D16, D20", varaleid: "T18, D19, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    133: { tegund: "Útgangur", maelt_med: "T19, T12, D20", varaleid: "T20, T11, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    134: { tegund: "Útgangur", maelt_med: "T20, D17, D20", varaleid: "T18, D20, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    135: { tegund: "Útgangur", maelt_med: "T19, D19, D20", varaleid: "T15, DB, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    136: { tegund: "Útgangur", maelt_med: "T20, T12, D20", varaleid: "T19, T13, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    137: { tegund: "Útgangur", maelt_med: "T19, D20, D20", varaleid: "D20, T19, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    138: { tegund: "Útgangur", maelt_med: "T20, D19, D20", varaleid: "T16, DB, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    139: { tegund: "Útgangur", maelt_med: "T20, T13, D20", varaleid: "T19, T14, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    140: { tegund: "Útgangur", maelt_med: "T20, D20, D20", varaleid: "D20, T20, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    141: { tegund: "Útgangur", maelt_med: "T17, DB, D20", varaleid: "DB, T17, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    142: { tegund: "Útgangur", maelt_med: "T20, T14, D20", varaleid: "T19, T15, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    143: { tegund: "Útgangur", maelt_med: "T20, T17, D16", varaleid: "T19, T18, D16", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    144: { tegund: "Útgangur", maelt_med: "T18, DB, D20", varaleid: "DB, T18, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    145: { tegund: "Útgangur", maelt_med: "T20, T15, D20", varaleid: "T19, T16, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    146: { tegund: "Útgangur", maelt_med: "T20, T18, D16", varaleid: "T19, T19, D16", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    147: { tegund: "Útgangur", maelt_med: "T19, DB, D20", varaleid: "DB, T19, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    148: { tegund: "Útgangur", maelt_med: "T20, T16, D20", varaleid: "T19, T17, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    149: { tegund: "Útgangur", maelt_med: "T20, T19, D16", varaleid: "T19, T20, D16", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    150: { tegund: "Útgangur", maelt_med: "T20, DB, D20", varaleid: "DB, T20, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    151: { tegund: "Útgangur", maelt_med: "T20, T17, D20", varaleid: "T19, T18, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    152: { tegund: "Útgangur", maelt_med: "T20, T20, D16", varaleid: "T20, T18, D19", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    153: { tegund: "Útgangur", maelt_med: "T20, T19, D18", varaleid: "T19, T20, D18", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    154: { tegund: "Útgangur", maelt_med: "T20, T18, D20", varaleid: "T19, T19, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    155: { tegund: "Útgangur", maelt_med: "T20, T19, D19", varaleid: "T19, T20, D19", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    156: { tegund: "Útgangur", maelt_med: "T20, T20, D18", varaleid: null, athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    157: { tegund: "Útgangur", maelt_med: "T20, T19, D20", varaleid: "T19, T20, D20", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    158: { tegund: "Útgangur", maelt_med: "T20, T20, D19", varaleid: "T20, T16, DB", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    159: { tegund: "Uppsetning (bogey)", maelt_med: "S20, T13, T20", varaleid: "S19, T17, T19", athugasemd: "Skora 119 til að skilja eftir 40. Markmið: breyta bogey í þægilegan útgang á næstu umferð." },
    160: { tegund: "Útgangur", maelt_med: "T20, T20, D20", varaleid: "T20, DB, DB", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    161: { tegund: "Útgangur", maelt_med: "T20, T17, DB", varaleid: "T19, T18, DB", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    162: { tegund: "Uppsetning (bogey)", maelt_med: "S20, T14, T20", varaleid: "S19, T17, T20", athugasemd: "Skora 122 til að skilja eftir 40. Markmið: breyta bogey í þægilegan útgang á næstu umferð." },
    163: { tegund: "Uppsetning (bogey)", maelt_med: "S18, T17, T18", varaleid: "S20, T17, T20", athugasemd: "Skora 123 til að skilja eftir 40. Markmið: breyta bogey í þægilegan útgang á næstu umferð." },
    164: { tegund: "Útgangur", maelt_med: "T20, T18, DB", varaleid: "T19, T19, DB", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    165: { tegund: "Uppsetning (bogey)", maelt_med: "S20, T17, T18", varaleid: "S19, T18, T20", athugasemd: "Skora 125 til að skilja eftir 40. Markmið: breyta bogey í þægilegan útgang á næstu umferð." },
    166: { tegund: "Uppsetning (bogey)", maelt_med: "S18, T17, T19", varaleid: "S20, T18, T20", athugasemd: "Skora 126 til að skilja eftir 40. Markmið: breyta bogey í þægilegan útgang á næstu umferð." },
    167: { tegund: "Útgangur", maelt_med: "T20, T19, DB", varaleid: "T19, T20, DB", athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." },
    168: { tegund: "Uppsetning (bogey)", maelt_med: "S20, T17, T19", varaleid: "S19, T19, T20", athugasemd: "Skora 128 til að skilja eftir 40. Markmið: breyta bogey í þægilegan útgang á næstu umferð." },
    169: { tegund: "Uppsetning (bogey)", maelt_med: "S18, T17, T20", varaleid: "S20, T19, T20", athugasemd: "Skora 129 til að skilja eftir 40. Markmið: breyta bogey í þægilegan útgang á næstu umferð." },
    170: { tegund: "Útgangur", maelt_med: "T20, T20, DB", varaleid: null, athugasemd: "Ljúktu á tvöfaldri (D) eða bull (DB)." }
};

/**
 * Get checkout advice for a given score
 * @param {number} score - Remaining score (2-170)
 * @returns {Object|null} - Advice object or null if no advice available
 */
function getCheckoutAdvice(score) {
    if (score < 2 || score > 170) {
        return null;
    }
    
    return checkoutAdvice[score] || null;
}
